name: Deploy Sashakt portal to staging

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: staging

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build application
        run: pnpm run build

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |

            cd /home/ubuntu/sashakt-portal

            git pull origin main
            pnpm install --production
            pnpm run build

            if [ -f "build/index.js" ]; then
              pm2 restart sashakt-portal --update-env || pm2 start build/index.js --name sashakt-portal
            else
              echo "Build output not found: build/index.js"
              exit 1
            fi
